//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProGamer.BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRating
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int UserId { get; set; }
        public int Note { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateUtcInsert { get; set; }
        public Nullable<System.DateTime> DateUtcUpdate { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
