//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProGamer.BackEnd.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> ListAccount { get; set; }
        public virtual DbSet<AccountType> ListAccountType { get; set; }
        public virtual DbSet<Chat> ListChat { get; set; }
        public virtual DbSet<ChatMessage> ListChatMessage { get; set; }
        public virtual DbSet<Course> ListCourse { get; set; }
        public virtual DbSet<CourseCategory> ListCourseCategory { get; set; }
        public virtual DbSet<CourseRating> ListCourseRating { get; set; }
        public virtual DbSet<Game> ListGame { get; set; }
        public virtual DbSet<Payment> ListPayment { get; set; }
        public virtual DbSet<PaymentStatus> ListPaymentStatus { get; set; }
        public virtual DbSet<PaymentType> ListPaymentType { get; set; }
        public virtual DbSet<Purchase> ListPurchase { get; set; }
        public virtual DbSet<Wallet> ListWallet { get; set; }
        public virtual DbSet<AspNetUsers> ListAspNetUsers { get; set; }
    }
}
