//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProGamer.BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public int PaymentTypeId { get; set; }
        public int UserId { get; set; }
        public int CourseId { get; set; }
        public int PaymentId { get; set; }
        public int PaymentStatusId { get; set; }
        public string Code { get; set; }
        public System.DateTime DatePurchase { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual PaymentStatus PaymentStatus { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual User User { get; set; }
    }
}
